CHECKPOINT = "checkpoints/epoch={epoch}/"
STATE_FILES = CHECKPOINT + "states/"
IMAGE_FILES = CHECKPOINT + "images/"
EVALUATION_FILES = CHECKPOINT + "evaluations/"
MODEL_STATE_DICT = STATE_FILES + "model_state_dict.json"
OPTIMIZER_STATE_DICT = STATE_FILES + "optimizer_state_dict.json"
SCHEDULER_STATE_DICT = STATE_FILES + "scheduler_state_dict.json"
